### DISCUSSION TITLE
Help for newbie to customise YAML file content

### DISCUSSION THREAD

**Discussion by myhillman** [aaubry/YamlDotNet#1039] [Q&A]
I need some help, and I need a VB.NET solution. Definitely a newbie as it's my first day with Yamldotnet.

I have a SortedDictionary populated with objects of class LASERcmd. It is defined by

Private LASERcmds As New SortedDictionary(Of Integer, LASERcmd) From { . . . . .

The definition of LASERcmd is below. When I serialize it I get the correct output (only two records shown for brevity) but it lacks a little in it's human readableness.

1. How can I convert the first number, which is the dictionary key, to hex? and presumably need to convert from hex to decimal when I deserialize.
2. How can I modify the Typ string to only include the base type, e.g. Typ: MOL.OnOffSteps, MOL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null => Typ: OnOffSteps
3. How can I change the scale to be fewer significant figures?

I have a feeling that all 3 questions will be a minor variation on the same answer, so some help with at least the first question would be much appreciated. I've spent a few hours attempting a custom converter, but most examples ar not VB.NET

TIA

**YAML output**
```
-2147483322:
  Mnemonic: ENGLSR
  description: Engraving On/Off pattern
  ParameterType: VARIABLE
  Parameters:
  - Name: List of steps
    Description: List of On/Off patterns
    Typ: MOL.OnOffSteps, MOL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Scale: 0.007937500000000002
    Units: mm
-2147481274:
  Mnemonic: MCBLK
  description: Motion Block
  ParameterType: FIXED
  Parameters:
  - Name: Size
    Description: Number of words
    Typ: System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
    Scale: 1
    Units: Words
```

**Class definition**
```
Class LASERcmd
    Property Mnemonic As String
    Property description As String
    Property ParameterType As ParameterCount = ParameterCount.FIXED       ' VARIABLE OR FIXED
    Property Parameters As New List(Of Parameter)    ' the type of the parameter

    Sub New(mnemonic As String, description As String)
        Me.Mnemonic = mnemonic
        Me.description = description
    End Sub

    Sub New(Mnemonic As String, description As String, pc As ParameterCount)
        Me.Mnemonic = Mnemonic
        Me.ParameterType = pc
        Me.description = description
    End Sub
    Sub New(Mnemonic As String, description As String, pc As ParameterCount, p As List(Of Parameter))
        Me.Mnemonic = Mnemonic
        Me.Parameters = p
        Me.ParameterType = pc
        Me.description = description
    End Sub
End Class
```
