### DISCUSSION TITLE
Keep native types after conversion to json

### DISCUSSION THREAD

**Discussion by mieliespoor** [aaubry/YamlDotNet#1051] [General]
I have been using this library to convert yaml to json, but it appears that integers and boolean values are converted to string in the resulting json.

source:
```yaml
run:
  concurrency: 8
  deadline: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
```

result:
```json
{
  "run": {
    "concurrency": "8",
    "deadline": "3m",
    "issues-exit-code": "1",
    "tests": "true",
    "skip-dirs": [
      "vendor",
      ".go"
    ]
  },
  "output": {
    "format": "colored-line-number",
    "print-issued-lines": "true",
    "print-linter-name": "true"
  }
}
```

expected:
```json
{
  "run": {
    "concurrency": 8,
    "deadline": "3m",
    "issues-exit-code": 1,
    "tests": true,
    "skip-dirs": [
      "vendor",
      ".go"
    ]
  },
  "output": {
    "format": "colored-line-number",
    "print-issued-lines": true,
    "print-linter-name": true
  }
}
```

What settings should be passed so that valid json would be produced? The issue we see is that converted json does not pass schema validations which causes failures.
