### DISCUSSION TITLE
Encountered an unresolved tag '!reference

### DISCUSSION THREAD

**Discussion by marais-vzc** [aaubry/YamlDotNet#1057] [Q&A] [answered]
Given the yaml:

```yaml
variables:
  JAVA_JDK_VERSION: 17
  BUILD_NUMBER_OFFSET: 500
  
include:
  - project: "eng-systems/templates"
    file: "/build-types/java-lambda.yml"

octopus-deploy-release:
  rules:
    - !reference [.run_never, rules]
```
And the code:
```cs
var deserializer = new DeserializerBuilder()
        .WithNamingConvention(CamelCaseNamingConvention.Instance)
        .WithAttemptingUnquotedStringTypeDeserialization()
        .Build();

return deserializer.Deserialize<object>(reader);
```

We are seeing the error: `Encountered an unresolved tag '!reference`.

Now, [GitLab says](https://docs.gitlab.com/ci/yaml/yaml_optimization/#configure-your-ide-to-support-reference-tags) we can simply add the following to `.vscode/settings.json`:

```
{
  "yaml.customTags": ["!reference sequence"]
}
```

How do we account for this using the `DeserializerBuilder`? I tried to add `.WithNodeTypeResolver(new MapTagsToObject())` (See [here](https://github.com/aaubry/YamlDotNet/issues/615#issuecomment-861575357)) without success. 

Anything else that could be tried?

**Comment by EdwardCooke** [comment, marked as answer]
You would use the `.WithTagMapping` method on the `DeserializerBuilder`.
You can do `string` instead of `object` and get the same result, just depends on what you want it to be in the end result.
For example:

```csharp
var yaml = """
    variables:
      JAVA_JDK_VERSION: 17
      BUILD_NUMBER_OFFSET: 500

    include:
      - project: "eng-systems/templates"
        file: "/build-types/java-lambda.yml"

    octopus-deploy-release:
      rules:
        - !reference [.run_never, rules]
    """;

var deserializer = new DeserializerBuilder()
        .WithNamingConvention(CamelCaseNamingConvention.Instance)
        .WithAttemptingUnquotedStringTypeDeserialization()
        .WithTagMapping("!reference", typeof(object[]))
        .Build();
```

Note, with the unquoted brackets it'll see it as an array. This serializes it to effectively the same yaml
```csharp
var o = deserializer.Deserialize<object>(yaml);
var serializer = new SerializerBuilder()
    .WithNamingConvention(CamelCaseNamingConvention.Instance)
    .WithTagMapping("!reference", typeof(object[]))
    .Build();
var x = serializer.Serialize(o);
Console.WriteLine(x);
```

Result:
```yaml
variables:
  JAVA_JDK_VERSION: 17
  BUILD_NUMBER_OFFSET: 500
include:
- project: eng-systems/templates
  file: /build-types/java-lambda.yml
octopus-deploy-release:
  rules:
  - !reference
    - .run_never
    - rules
```
