### DISCUSSION TITLE
Mutliple classes for the same interface with Dictionary<string, ITask>

### DISCUSSION THREAD

**Discussion by Cedange** [aaubry/YamlDotNet#628] [Q&A]
Hello, and thank you for this wonderful API.

I'm struggling trying to have a dictionary with different items implementing the same interface. If I have TaskA and TaskB implementing ITask, I successfully serialize my .yml but can't deserialize it. I tried with IObjectFactory, but I 'don't have enough context to know which constructor to call. I also tried with INodeDeserializer, and had the same issue. The key of the dictionary is almost the type name. I can't use tag, because I'm not the only owner of the yaml.

```
tasks:
  taskA:
    type: "taskA"
    amount: 10
  taskB:
    type: "taskB"
    address: "addressOfB"
```

Thank you for your help :)
