### DISCUSSION TITLE
Inherit from other yaml objects

### DISCUSSION THREAD

**Discussion by ThePROX** [aaubry/YamlDotNet#756] [Q&A]
I have a background in Ruby development and am now working in .net.  I am used to being able to do something like this in Ruby:

```yaml
foo: &foo
  key1: value 1
  key2: value 2
  key3: value 3
bar: &bar
  <<: foo
  key3:  value 4
```

When attempting to do this using YamlDotNet, I am having issues with the values not merging together correctly.  I would expect the outcome of bar above to be this:

```yaml
bar: 
  key1: value 1
  key2: value 2
  key3: value 4
```

instead I am ending up with:

```yaml
bar:
  key3: value 4
```

Any help with solving this would be greatly appreciated.  This is holding us back from completing our current project work.

Thanks!
