### DISCUSSION TITLE
Type descriminator for dictionary value by key

### DISCUSSION THREAD

**Discussion by dazinator** [aaubry/YamlDotNet#847] [General]
I'd like to deserialize some yaml into a type that has a polymorphic dictionary property.
I'd like to implement a scheme where by, when deserializing  `dictionary<string, BaseType>` I'd like to select the concrete type based on the dictionary key value.

It's not just a straight forward mapping however- I need to run some logic on the key value.

```
propertyA: foo
  myDictionary:
    objectOne@typeA:
        foo: bar
    objectTwo@typeB
        bar:  bat
    
```

So here I my type has a property called `MyDictionary` which is a `Dictionary<string, BaseType>`. I'd like to analyse / map the value of the key after the `@` to work out what type should be selected for deseriliazation. Is this possible?

The docs suggest it may not be.

**Comment by dazinator** [comment]
The desire for this is that:

- I want to use a dictionary to ensure there cannot be duplicate keys added by the user.
- - I want to use polymorphism so I can extend the subtypes to support different planned features.
- I want to include the type descriminator in the key because I see this as part of the identity of the object, e.g adding two items to the dictionary with the same name but different types should be allowed hence the type + name should be part of the key.. without this, this would not be valid:

```
propertyA: foo
  myDictionary:
    foo:
        type: typeA
        foo: bar
    foo:
        type: typeB
        bar:  bat
```

I want that to be valid so I want the type as part of the key:


```
propertyA: foo
  myDictionary:
    foo@typeA:
        foo: bar
    foo@typeB:
        bar:  bat
```

Now there is no problem.
I could ofcourse still use this "foo@typeA" convention but if I cant use it for type descriminator then I'd have to repeat the type as a property also to support type descriminator and this is just added room for errors and seems like undesirable repetition:

```
propertyA: foo
  myDictionary:
    foo@typeA:
        type: typeA
        foo: bar
    foo@typeB:
        type: typeB
        bar:  bat
```
