### DISCUSSION TITLE
Any way of getting rid of object references and simply repeat?  The YAML is for humans to read.

### DISCUSSION THREAD

**Discussion by webJose** [aaubry/YamlDotNet#882] [Q&A] [answered]
So I have this struct that tells me the type of database object with an enum `Type` property and a `Name` string property.  Then I have a class, `PotentialReference` with a `Type` property of this struct.

The YAML is generating using object references for the types:

```yaml
  - objectSchema: dbo
    objectName: GetEOCData
    type: *o1
    potentialReferences: []
```

That should ideally be:

```yaml
  - objectSchema: dbo
    objectName: GetEOCData
    type:
      type: IL
      name: Inline function
    potentialReferences: []
```
This should be everywhere since the YAML is meant for humans.

Also, how do I tell the serializer not to output empty `potentialReferences` collections like the one in the example?
