### DISCUSSION TITLE
Need help on deserialization

### DISCUSSION THREAD

**Discussion by AlexCastroAlex** [aaubry/YamlDotNet#929] [Q&A]
Hello all , 

I need help on deserialization of a yaml file with properties like these : 
```yaml
paths:
  cam1hd:
    record: 'yes'
    recordPath: \\192.168.10.32\recordings\%path\%Y-%m-%d_%H-%M-%S-%f
    recordFormat: fmp4
    recordPartDuration: 100ms
    recordSegmentDuration: 3m
    recordDeleteAfter: 30m
    source: 'rtsp://admin:Abc12345@172.26.1.10/Streaming/Channels/1'
  cam2hd:
    source: 'rtsp://admin:Abc12345@172.26.1.25/main'
```

The representation of the C# entity is  : 

```csharp
  public partial class Paths
  {
      public Dictionary<string, CamVt> camVt { get; set; }

      [YamlMember(Alias = "all_others", ApplyNamingConventions = false)]
      public object AllOthers { get; set; }
  }

  public partial class CamVt
  {
      [YamlMember(Alias = "source", ApplyNamingConventions = false)]
      public string Source { get; set; }
  }
  public partial class Cam1Remote:CamVt
  {
      [YamlMember(Alias = "record", ApplyNamingConventions = false)]
      public string Record { get; set; }

      [YamlMember(Alias = "recordPath", ApplyNamingConventions = false)]
      public string RecordPath { get; set; }

      [YamlMember(Alias = "recordFormat", ApplyNamingConventions = false)]
      public string RecordFormat { get; set; }

      [YamlMember(Alias = "recordPartDuration", ApplyNamingConventions = false)]
      public string RecordPartDuration { get; set; }

      [YamlMember(Alias = "recordSegmentDuration", ApplyNamingConventions = false)]
      public string RecordSegmentDuration { get; set; }

      [YamlMember(Alias = "recordDeleteAfter", ApplyNamingConventions = false)]
      public string RecordDeleteAfter { get; set; }
  }
```

The idea is that cam1hd could be whatever name  and has properties below, that's why i created a  Dictionary<string, CamVt>. 
And the camVt entity could be inherited to be a Dictionary<string, Cam1Remote>.

I was not able to deserialize this file because of this specificity.

Anybody could help please ? 🙏

Regards
