### DISCUSSION TITLE
Is it possible to retain the order of the object when serializing

### DISCUSSION THREAD

**Discussion by devantler** [aaubry/YamlDotNet#974] [Q&A] [answered]
I am using YAMLDotnet to build a [devantler/dotnet-kubernetes-generator](https://github.com/devantler/dotnet-kubernetes-generator), which is a library to generate Kubernetes API resources as well as custom resources. I am building this library as I need it for a new feature (generate Kubernetes resources with `ksail gen <name-of-resource>`) in my OS project [devantler/ksail](https://github.com/devantler/ksail).

When serializing objects, the order is changed such that the serialized object is in lexical order. I would like to retain the order such that for example Kubernetes Secrets look like this:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: default
type: Opaque
data: {}
```

And not this:

```yaml
---
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: secret
  namespace: default
type: Opaque
```

Is it possible to change the serialization to keep the order of the object:

```csharp
var model = new V1Secret
{
  ApiVersion = "v1",
  Kind = "Secret",
  Metadata = new V1ObjectMeta
  {
    Name = "secret",
    NamespaceProperty = "default"
  },
  Type = "Opaque",
  Data = new Dictionary<string, byte[]>
  {
  }
};
```

**Comment by EdwardCooke** [comment]
You may need to use a custom yaml converter. I suspect you’re using the kubernetes client library classes so putting on the yamlmember attribute isn’t a possibility. 

The yaml converters allow you to serialize and deserialize exactly the way you want.

**Reply by devantler** [reply]
I am using this wrapper around YamlDotNet, so the Kubernetes client library classes are no issue: https://github.com/IvanJosipovic/YamlDotNet.System.Text.Json

Thank's I will see if I can cook up a converter for the purpose. K8s yaml looks pretty ew, when its mixed like that 😬

**Comment by EdwardCooke** [comment, marked as answer]
My guess, based on your example, is that it has something to do with this line in that library that is causing you problems:

[            .WithTypeConverter(new SystemTextJsonYamlTypeConverter(sortAlphabetically))](https://github.com/IvanJosipovic/YamlDotNet.System.Text.Json/blob/1a986cbb0821596428d8717a6188a59b4845929e/src/YamlDotNet.System.Text.Json/YamlConverter.cs#L13)

Our library typically serializes in the order of the properties as they are declared in the class by default. But there's no guarantees. It's really in whatever order they are returned in the reflection calls or dictionary/list.

**Reply by devantler** [reply]
Thanks! I will play around with it a bit when time allows, and see if I can find a solution I like. I am mostly concerned with the root object returning the boilerplate at the top, in this order:

```yaml
apiVersion: <api-version>
kind: <kind>
metadata:
  <metadata-elements>
```

Given that is the order I create the non-serialized objects in, I believe disabling the alphabetical sort is fine :-) It might still cause elements of list and dictionaries to come in a random order, but that is a non-issue I believe.

**Reply by devantler** [reply]
Hmm, without the other library I still get a funny order:

```csharp
ISerializer _serializer = new SerializerBuilder()
    .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
    .WithNamingConvention(CamelCaseNamingConvention.Instance).Build();

var model = new V1Secret
{
  ApiVersion = "v1",
  Kind = "Secret",
  Metadata = new V1ObjectMeta
  {
    Name = "secret",
    NamespaceProperty = "default"
  },
  Type = "Opaque",
  Immutable = true,
  Data = new Dictionary<string, byte[]>
  {
    ["key"] = Encoding.UTF8.GetBytes("value")
  },
  StringData = new Dictionary<string, string>
  {
    ["key"] = "value"
  }
};

string yaml = _serializer.Serialize(model);

await File.WriteAllTextAsync(outputPath, yaml, cancellationToken).ConfigureAwait(false);
```

Output:

```yaml
---
apiVersion: v1
data:
  key:
  - 118
  - 97
  - 108
  - 117
  - 101
immutable: true
kind: Secret
metadata:
  name: secret
  namespaceProperty: default
stringData:
  key: value
type: Opaque
```

The sortAlphabetically bool did not have an effect in the other library.

> Our library typically serializes in the order of the properties as they are declared in the class by default. But there's no guarantees. It's really in whatever order they are returned in the reflection calls or dictionary/list.

It seems that is what is causing my issues. I will cook something up to solve it in my library, and if it is not too specific to my use case, I can consider doing a PR if you want :-)
