### ISSUE TITLE
How do I handle the content represented by an anchor in an IYamlConverter?

### ISSUE THREAD

**Issue by Polar-Pumpkin** [aaubry/YamlDotNet#1045]
It seems that the anchor of yaml cannot be used to insert content into a list, so I want to reference repeated content and add new content to the list by converting it into a nested list.

For example, considering this yaml:
```yaml
executors:
  - name: a
    filters: &shared
      - type: foo
        value: 1
      - type: bar
        value: 2
  - name: b
    filters: 
      - *shared
      - type: extra
        value: 3
```

I expected to parsing like:
```yaml
executors:
  - name: a
    filters: &shared
      - type: foo
        value: 1
      - type: bar
        value: 2
  - name: b
    filters: 
      - - type: foo
          value: 1
        - type: bar
          value: 2
      - type: extra
        value: 3
````

I wrote an IYamlConverter to manually parse this list. Originally, I thought that the anchor would be directly converted into a repeated `ParsingEvent` queue, but what I actually got was an `AnchorAlias` ​​event and the name of the anchor. How can I get the content represented by this anchor?

This code will getting exception: `Unhandled exception. (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type YamlAnchorTest.Filter, YamlAnchorTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

```csharp
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace YamlAnchorTest;

public class Configuration {
    public List<Executor> Executors { get; set; }
}

public class Executor {
    public string Name { get; set; }
    public List<Filter> Filters { get; set; }
}

public class Filter {
    public string Type { get; set; }
    public int Value { get; set; }
}

public class FilterCollectionConverter : IYamlTypeConverter {
    public static IYamlTypeConverter Instance { get; } = new FilterCollectionConverter();

    public bool Accepts(Type type) {
        return type == typeof(List<Filter>);
    }

    public object ReadYaml(IParser parser, Type type, ObjectDeserializer rootDeserializer) {
        var result = new List<Filter>();
        parser.Consume<SequenceStart>();
        while (!parser.TryConsume<SequenceEnd>(out _)) {
            // Got AnchorAlias here! With nothing else but anchor name?
            if (parser.TryConsume<SequenceStart>(out _)) {
                while (!parser.TryConsume<SequenceEnd>(out _)) {
                    result.Add((Filter)rootDeserializer.Invoke(typeof(Filter))!);
                }
            }

            result.Add((Filter)rootDeserializer.Invoke(typeof(Filter))!);
        }

        return result;
    }

    public void WriteYaml(IEmitter emitter, object? value, Type type, ObjectSerializer serializer) {
        throw new NotImplementedException();
    }
}

internal static class Program {
    private static void Main(string[] args) {
        var document =
            """
            executors:
              - name: a
                filters: &shared
                  - type: foo
                    value: 1
                  - type: bar
                    value: 2
              - name: b
                filters: 
                  - *shared
                  - type: extra
                    value: 3
            """;
        var deserializer = new DeserializerBuilder()
            .WithTypeConverter(FilterCollectionConverter.Instance)
            .WithNamingConvention(HyphenatedNamingConvention.Instance)
            .WithEnumNamingConvention(HyphenatedNamingConvention.Instance)
            .Build();
        var conf = deserializer.Deserialize<Configuration>(document);
    }
}
```
