### ISSUE TITLE
Attribute Based Naming Convention

### ISSUE THREAD

**Issue by shaun-turner-hitcs** [aaubry/YamlDotNet#1056]
**Is your feature request related to a problem? Please describe.**
At present, the naming conventions all assume that you're converting from one naming convention to another, this is fine in most cases, but there are times where you need to be a little more flexible. Sometimes, for example you don't have ownership of the classes being serialized or deserialized. Other times you may want something more user friendly or readable.

**Describe the solution you'd like**
The Json Serializers have a concept of using Custom Attributes **JsonPropertyNameAttribute** to identify the name that is assigned

If YamlDotNet had this capability it would mean that the **INamingConvention** interface would be changed to accept reflected type information instead of just the string names of the properties, this would then allow me to create a class in my own libraries that leveraged the existing **JsonPropertyAttribute** and others could do the same for their own implementations.

**Describe alternatives you've considered**
I've looked at changing the names to match the casing but sadly this is simply not possible.

**Additional context**
One example is that I would like to be able to serialize the kubernetes objects from the kubernetes client libraries into yaml to make human readable examples available in my test projects. However the kubernetes library defines a property called NamespaceProperty, in json this is serialized as namespace.

```yaml
apiVersion: kadense.io/v1
kind: MalleableModule
metadata:
  name: example
  namespaceProperty: kadense
spec:
   ...
```

However kubernetes expects **namespace** as follows:

```yaml
apiVersion: kadense.io/v1
kind: MalleableModule
metadata:
  name: example
  namespace: kadense
spec:
   ...
```

Obviously I cannot change kubernetes, nor do I really want to change the kubernetes client, so this seems like the least amount of work (I am happy to contribute)
