### ISSUE TITLE
Deserializing multiple documents in one file PLUS TAGS

### ISSUE THREAD

**Issue by derFunk** [aaubry/YamlDotNet#140]
Hi,

it seems that the combination of having multiple documents in a single file and using tags for all the nested documents does not work.
This is the case for serialized scene files from Unity.

The reason obviously is that the %TAG definition is only read once for the first nested document, but not for the following ones, resulting in a `While parsing a node, find undefined tag handle.` exception.

Testfile:
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
SceneSettings:
  m_ObjectHideFlags: 0
--- !u!104 &2
RenderSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 6
  m_Fog: 0
--- !u!127 &3
LevelGameManager:
  m_ObjectHideFlags: 0
--- !u!157 &4
LightmapSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 5
```

I implemented a NodeTypeResolver to resolve the Unity integer class mappings.
Source code here: https://gist.github.com/derFunk/795d7a366627d59e0dbd

(You'd need UnityEngine.dll referenced in your test project which you can get from the [free Unity download](http://beta.unity3d.com/download/f0a33a6ef422/Windows64EditorInstaller/UnitySetup64-5.1.3p3.exe), and you don't even have to install Unity - just open the installer exe in 7zip and grab it from `$_OUTDIR\Managed\UnityEngine.dll` - easy.)

My test code:
```csharp
void Start(string searchFolder)
{
	var deserializer = new Deserializer();

	// put my resolver first!
	// this is only necessary because another bug:
	// TypeNameInTagNodeTypeResolver needs an update to
	// return false when "Type.GetType" throws an exception, in order to pass on the
	// resolving to the next resolver
	var oldResolvers = new INodeTypeResolver[deserializer.TypeResolvers.Count];
	deserializer.TypeResolvers.CopyTo(oldResolvers, 0);
	deserializer.TypeResolvers.Clear(); // copies entries to oldResolvers!
	deserializer.TypeResolvers.Add(new UnityNodeTypeResolver());
	foreach (var nodeTypeResolver in oldResolvers)
		deserializer.TypeResolvers.Add(nodeTypeResolver);

	try
	{
		var yamlText = File.ReadAllText("scenefile.unity");
		var reader = new EventReader(new Parser(new StringReader(yamlText)));
		
		// important for reading multiple documents in one file (stream)
		// see also https://github.com/aaubry/YamlDotNet/issues/12
		reader.Allow<StreamStart>();

		while (!reader.Accept<StreamEnd>())
		{
			// first test deserialization
			var obj = deserializer.Deserialize(reader);
		}
		// do something
	}
	catch (Exception e)
	{
		Console.Writeline(file + ": " + e);
		Environment.Exit(1);
	}
}
```

**Comment by derFunk** [comment]
May be related to this PR: https://github.com/aaubry/YamlDotNet/pull/102

**Comment by derFunk** [comment]
Meta Info: Unity files still are not parseable if they contain the "stripped" keyword after the document boundary marker - see also http://forum.unity3d.com/threads/scene-files-invalid-yaml.355653/.

Not sure if that's a violation of the specification and thus invalid YAML documents Unity produces.

**Comment by derFunk** [comment]
If anybody has feedback on validity of the Unity scene file format, let me know!

Is this valid YAML?
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!4 &41387171 stripped
Transform:
m_PrefabParentObject: {fileID: 476688, guid: d1cbe4ee1e40dbb46aa458321c1b846a, type: 2}
m_PrefabInternal: {fileID: 41387170}
```
