### ISSUE TITLE
RegisterTagMapping for serialiser

### ISSUE THREAD

**Issue by tomitrescak** [aaubry/YamlDotNet#145]
Hi, thanks for the very awesome library! 
I have a bit of issue in producing human readable YAML, when inherited types are in play.
Using "Roundtrip" option I get output similar to this:

``` yaml
!System.Collections.Generic.List%601[[Ei.Persistence.ArcDao,%20Ei,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null]],%20mscorlib,%20Version=4.0.0.0,%20Culture=neutral,%20PublicKeyToken=b77a5c561934e089
- Properties: []
  Id: 1
- !Ei.Persistence.ArcWorkflowDao,%20Ei,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
  WorkflowId: 2
  Properties: []
- !Ei.Persistence.ArcActionDao,%20Ei,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
  ActionId: 4
  Properties: []
```

While this can be easily deserialised, the readability of such YAML is reduced.
Deserialiser has a very nice option to register tag mappings. 

``` csharp
deserializer.RegisterTagMapping("!wfarc", typeof(ArcWorkflowDao));
deserializer.RegisterTagMapping("!actionArc", typeof(ArcActionDao));
```

With this mapping the above YAML can be cleared to:

``` yaml
- Properties: []
  Id: 1
- !wfarc
  WorkflowId: 2
  Properties: []
- !actionArc
  ActionId: 4
  Properties: []
```

This is parsed with no issues and YAML shines. Is there any possibility to modify serialiser's behaviour to emit registered tags in the short form and not emit all the other assembly information?

Thanks
