### ISSUE TITLE
Representation model anchors

### ISSUE THREAD

**Issue by bondsbw** [aaubry/YamlDotNet#155]
After building up the representation model of the following document, the YamlNode.Anchor property appears to be null everywhere.  Specifically I can't find the anchor `&mammal_ref` on the `mammal` node.

Also, is there a way to determine that `beaver` is built from the reference `*mammal_ref`?

``` yaml
mammal: &mammal_ref
 warm_blooded: true
 lays_eggs: false

beaver: *mammal_ref

otter:
 cute: true
 <<: *mammal_ref

platypus:
 <<: *mammal_ref
 lays_eggs: true
```

I tried all of this using deserialization instead.  It creates the same object for `mammal` and `beaver`, and I can test reference equality to figure out if a reference was used.  I couldn't test `otter` and `platypus` because those threw an exception related to token `<<`.

Thanks in advance for the help!

(Apologies if I'm just being a noob; I just started using YamlDotNet today.)
