### ISSUE TITLE
Empty string not serialized

### ISSUE THREAD

**Issue by npateman** [aaubry/YamlDotNet#157]
I have a document which has the following section in it,

```
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
```

If I deserialise that section and then serialise it again it comes out like this,

```
defaults:
- scope:
    path: 
    type: pages
  values:
    layout: page
    comments: true
- scope:
    path: 
    type: posts
  values:
    layout: post
    comments: true
```

The problem is that I need the pairs of quotes in the path fields ("") to denote an empty string.  Is there some configuration option I need to change to achieve this?

Nick.
