### ISSUE TITLE
Different syntax for handling properties filled with interfaces or inheriting types

### ISSUE THREAD

**Issue by artyom-zuev** [aaubry/YamlDotNet#211]
Let's say we have a **Dictionary<int, **MyBaseClass**> myDictionary*\* property in a serialized class, where **MyBaseClass** is a reference type. We then have two classes inheriting from **MyBaseClass**: **MyInheritingClassA** and **MyInheritingClassB**, each with different properties, which are used for values in that dictionary. YAMLDotNet has no trouble serializing such a dictionary to this:

```
myDictionary:
      0:
        floatProperty: 2.75
        boolProperty: true
      1:
        integerProperty: 5
        stringProperty: "Lorem ipsum"
```

There is a problem with that serialization result, of course - it gives the deserializer no way of knowing that the objects in the dictionary actually aren't of **MyBaseClass** type. So the deserializer will predictably attempt to deserialize this structure into two **MyBaseClass** objects, and will stop, failing to find **floatProperty** in **MyBaseClass**. This can be solved by enabling the Roundtrip mode on the serializer, which would result in it emitting the following text:

```
myDictionary:
      0: !MyInheritingClassA,%20Assembly-CSharp,%20Version=0.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
        floatProperty: 2.75
        boolProperty: true
      1: !MyInheritingClassB,%20Assembly-CSharp,%20Version=0.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
        integerProperty: 5
        stringProperty: "Lorem ipsum"
```

Such an output would be perfectly deserialized into a **MyInheritingClassA** object at key 0 and **MyInheritingClassB** object at key 1. There is only one problem with this - such a verbose format isn't very friendly to manual edits and really clutters the file (if you have a collection with thousands of entries each containing some concise properties, that class info would account for 90% of text). So I started wondering if some simpler, more concise syntax can be used. Obviously, you can register custom tags on the deserializer and then easily read something like this:

```
myDictionary:
      0: !customTagA
        floatProperty: 2.75
        boolProperty: true
      1: !customTagB
        integerProperty: 5
        stringProperty: "Lorem ipsum"
```

Unfortunately, the serializer has no support for custom tags, so for something like an application config file, it's not a very useful approach - your nice tags will be removed on next serialization (or replaced with that verbose class info, as in the previous snippet if Roundtrip mode is enabled). So I started checking if it's possible to strip some parts of the Roundtrip mode type syntax. First, I tried this:

```
myDictionary:
      0: !MyInheritingClassA
        floatProperty: 2.75
        boolProperty: true
      1: !MyInheritingClassB
        integerProperty: 5
        stringProperty: "Lorem ipsum"
```

The deserializer ignored the class info written in that format and attempted to deserialize entries into **MyBaseClass**. No dice. Then I tried this:

```
myDictionary:
      0: !MyInheritingClassA,%20Assembly-CSharp
        floatProperty: 2.75
        boolProperty: true
      1: !MyInheritingClassB,%20Assembly-CSharp
        integerProperty: 5
        stringProperty: "Lorem ipsum"
```

It worked. So, apparently, version, culture and public key token parameters are optional and aren't necessary to resolve the entry to a proper class. Looks like those parameters are optional. So, I'm left wondering - why is more concise syntax not supported?

```
myDictionary:
      0: !MyInheritingClassA
        floatProperty: 2.75
        boolProperty: true
      1: !MyInheritingClassB
        integerProperty: 5
        stringProperty: "Lorem ipsum"
```

I understand that assembly, version, culture and token parameters might have some valid use cases, but it would be very nice to have an option of emitting YAML without them - just a type name over every custom type.

**Edit:** Investigated it a bit more - it looks like additional parameters aren't exactly intentional, they are just included by default into the output of the **Type.AssemblyQualifiedName** function used by the serializer in the Roundtrip mode. Replacing it with Type.Name at line 127 in TypeAssigningEventEmitter.cs turn the Rountrip-mode emitted YAML into the format I have suggested. Now to figure out how to make this deserialized.

**Edit 2:** Still not sure why the deserializer ignores the type tags containing no commas - as far as I understand, type-containing tags are handled by **TypeNameInTagNodeTypeResolver** class, and it contains nothing that would trigger than behaviour - it just grabs the **tag substring 1**, which should work with the example above. The tag might be discarded earlier, before that class gets a chance to work, I guess. Or maybe GetType called with that substring fails without any suffixes within an input, for some reason?

**Edit 3:** A-ha, looks like standard GetType returns null if the string you pass to it is not assembly-qualified. Since no info seems to be actually used from assembly parameters, GetType is probably just doing a simple check for the number of strings after a split by a comma character. Should be possible to use a different GetType method to sidestep that (maybe Assembly.GetType?). Trying that now.
