### ISSUE TITLE
object array not serialized.

### ISSUE THREAD

**Issue by bj0** [aaubry/YamlDotNet#26]
If I try to serialize an object array like so:

    var s = new Serializer();
    var tw = new StringWriter();
    s.Serialize(tw, new { Name="test", Item=new object[] { 1, 2, "3"} } );
    var output = tw.ToString()

I get output like this:

    Name: test
    Item: 
    - {}
    - {}
    - {}

It seems that it does not properly get the boxed values from the object array.

**Comment by tomkerkhove** [comment]
Is there a sample where this is illustrated? Would be perfect if it did serialization & deserialization.

This is something I currently have to do but a bit hard to find how to achieve this.

Example:
```yaml
items:
  - name: "abc"
    type: "Foo"
    description: "This is a sample"
  - name: "xyz"
    type: "Bar"
    url: "https://google.com"
```
