### ISSUE TITLE
yes/no values not being parsed as bool

### ISSUE THREAD

**Issue by Beatsleigher** [aaubry/YamlDotNet#289]
I've used YamlDotNet before, and I've never come across this issue before; however it seems as though YamlDotNet is parsing my booleans (serialised as yes/no) as strings, instead of booleans.

I've created a StackOverflow question [here](https://stackoverflow.com/questions/47213993/yamldotnet-not-parsing-yes-no-values), however no answers have come yet.

Basically, application configs are stored in YAML files, and are deserialized to a Dictionary<string, object> in an attempt to keep the application as modular as possible.

Here is an excerpt from the config file:
```yaml
# [SAMARIUM]
use_default_values: no
log_directory: ./logs/
plugin_directory: ./plugins/

# [SAMARIUM LOGGER]
log_to_console: yes # Disable for production
log_to_file: yes # Recommended to keep on

# [SAMARIUM REST]
rest_base_ip: 127.0.0.1 # Change to machine's local IP; e.g. 192.168.1.1 (IPv6 is welcome, too)
rest_listen_port: 80
```

This is the deserialising code:
```csharp
var deserializer = new DeserializerBuilder()
    .WithNamingConvention(new UnderscoredNamingConvention())
    .Build();

using (var reader = cfgFile.OpenText()) {
    cfgHashMap = deserializer.Deserialize<Dictionary<string, object>>(reader);
}
```

And finally the deserialised values in my hashmap:
![Image of deserialised values](https://i.stack.imgur.com/RDmQM.png)

___

Judging by the code referenced in #183 , these values should be deserialised without the use of any additional converters, mappers, etc?
I'm going to assume my theory is correct, because trying to register the ScalarNodeDeserializer results in a runtime exception (already registered). 

I'll do some more digging, but for now this seems like a bug in the API.

Full source code can be found [here](https://github.com/Beatsleigher/Samarium)
