### ISSUE TITLE
Deserializing a single value to an array

### ISSUE THREAD

**Issue by JonCanning** [aaubry/YamlDotNet#301]
I have a yaml file like this:

```
people:
  - name: John
    age: 30
    jobs:
      title: Manager
  - name: Dave
    age: 25
    jobs:
      - title: Cleaner
      - title: CTO
```

Jobs can either be a single object, or an array of objects. If the `Jobs` property is of type `Job[]` then I get the following error:

`Expected 'SequenceStart', got 'MappingStart'`

How can I convert a single object into an array?
