### ISSUE TITLE
Can I apply variable place holder resolver to Deserializer?

### ISSUE THREAD

**Issue by kenjiuno** [aaubry/YamlDotNet#321]
I am writing a program to generate Appcast.xml from a yaml definition like this:

```yaml
appcastXml: Appcast.xml
globs:
- pattern: Setup_MYAPP-*.exe
  sort: latest
  prefix: app
channels:
- title: MYAPP
  link: https://s3-ap-northeast-1.amazonaws.com/XXX/MYAPP/Appcast.xml
  description: MYAPP を配布します
  language: ja
  items:
  - title: New version
    pubDate: "{{app.lastModifiedUtc}}"
    url: "https://s3-ap-northeast-1.amazonaws.com/XXX/MYAPP/{{app.fileName}}"
    version: "{{app.shortVersion}}"
s3:
- profile: XXX-up
  bucket: XXX
  uploads:
  - from: "{{app.filePath}}"
    to: "MYAPP/{{app.fileName}}"
  - from: Appcast.xml
    to: MYAPP/Appcast.xml
```

However I need to call my `FormatVariablePlaceHolder` every time in order to resolve variable place holders included in yaml string data.
```c#
            XDocument rss = new XDocument(
                new XElement("rss"
                , model.channels.Select(
                    channel => new XElement("channel"
                        , new XElement("title", channel.title.FormatVariablePlaceHolder(vars))
                        , new XElement("link", channel.link.FormatVariablePlaceHolder(vars))
                        , new XElement("description", channel.description.FormatVariablePlaceHolder(vars))
                        , new XElement("language", channel.language.FormatVariablePlaceHolder(vars))
```

I want to apply `.FormatVariablePlaceHolder(vars)` for all of `string` member in my model.

Is there a good option to achieve this on YamlDotNet component?
