### ISSUE TITLE
Error Serializing Array of Objects

### ISSUE THREAD

**Issue by Dargmuesli** [aaubry/YamlDotNet#325]
I want this YAML to be generated:

```YAML
ports:
- target: 80
  published: 80
  protocol: tcp
  mode: host
- target: 443
  published: 443
  protocol: tcp
  mode: host
```
Which is equal to this JSON:

```JSON
"ports": [
  {
    "target": 80,
    "published": 80,
    "protocol": "tcp",
    "mode": "host"
  }, {
    "target": 443,
    "published": 443,
    "protocol": "tcp",
    "mode": "host"
  }
]
```

Instead, trying to serialize the JSON, I receive an `Exception calling "Serialize" with "1" argument(s): "Too much recursion when traversing the object graph"` using YamlDotNet 4.3.1. Am I doing something wrong or is this currently not supported by YamlDotNet?
