### ISSUE TITLE
Deserialize to YamlObject does not take type into consideration 

### ISSUE THREAD

**Issue by guy-lud** [aaubry/YamlDotNet#326]
Hi,
 
I wonder if the following scenario is by design:
The following Yaml has just one line 

version : 1

By Deserialize it to a YamlObject the value of yobject["version"] is "1" thus if we want to convert the yam,l into json we get type conversion issues.

Thanks

**Comment by philosowaffle** [comment]
+1

We are trying to use this for converting [OpenApi schemas](https://swagger.io/specification/) from yaml to json but the types are not honored causing invalid json schemas.

YAML
```
  parameters:
  - name: "request"
    in: "body"
    required: true
```

**Comment by andylholloway** [comment]
+2 
We are also using this to convert Yaml Open API doc into json, but when we reference the doc in https://editor.swagger.io we get a bunch of schema errors.

Example:
this is what we have in our Yaml:
```
parameters: 
 - name: name
   in: query
   required: true
   type: string
```

But the library deserialises to:
```
{
    "name": "name",
    "in": "query",
    "required": "true",
    "type": "string"
}
```
