### ISSUE TITLE
Question - Serializing & Deserializing objects with inheritance

### ISSUE THREAD

**Issue by tomkerkhove** [aaubry/YamlDotNet#341]
I'm trying to understand the serialization & deserialization of objects a bit and how this works with inheritance.

If I have a class `Factory`:
```csharp
public class Factory
{
    public List<ICar> Cars { get; } = new List<ICar>();
}
```

Where `ICar` specifies the following:
```csharp
public interface ICar
{
    string LicensePlate { get; set; }
    Make Make { get; set; }
}
```

Then I have different objects per car make such as `Ford`
```csharp
public class Ford : Car, ICar
{
    public Make Make { get; set; } = Make.Ford;
    public bool HasSpareTier { get; set; }
}
```

Which uses `Car`:
```csharp
public class Car
{
    public string LicensePlate { get; set; }
}
```

This perfectly serializes as following:
```yaml
cars:
- make: Ford
  hasSpareTier: true
  licensePlate: 4391bbc9-af5c-4f50-adf4-85a522508267
- isDiesel: true
  licensePlate: 311c11ea-ca03-4525-9f9a-56fa6764b100
- hasAutomaticBreak: true
  make: Volvo
  licensePlate: 53a5c3c9-04f3-4573-9e4b-48a63befbd19
```

Stupid questions inbound:
- How do I deserialize my objects so that I can cast them to `Ford` instead of `ICar`?
- Should I use the `YamlStream` instead and parse it myself? _This brings a lot of overhead that I would like to avoid ([sample](https://github.com/tomkerkhove/yaml-generics/blob/master/src/TomKerkhove.YamlGenerics.Tests/Serialization/FactorySerializer.cs))_

## NuGet Version
`YamlDotNet` v5.0.1

## Full Repro
You can find a repro of what I want to achieve [here](https://github.com/tomkerkhove/yaml-generics/blob/master/src/TomKerkhove.YamlGenerics.Tests/BuilderSerializationTests.cs)

This currently throws an exception but I'm honestly not sure why:
> SerializationException: Property 'cars' not found on type TomKerkhove.YamlGenerics.Tests.Model.Factory'.
