### ISSUE TITLE
How to include YAML file inside another YAML file?

### ISSUE THREAD

**Issue by veraciousnottaken** [aaubry/YamlDotNet#368]
Basically like in question on SO: [How can I include a YAML file inside another?](https://stackoverflow.com/a/9577670/1296687)

`foo.yaml`

``` YAML
a: 1
b:
    - 1.43
    - 543.55
c: !include bar.yaml
```

`bar.yaml`

``` YAML
- 3.6
- [1, 2, 3]
```

Result in memory:

``` YAML
a: 1
b:
    - 1.43
    - 543.55
c: 
   - 3.6
   - [1, 2, 3]
```
