### ISSUE TITLE
Mapping values are not allowed in this context error on similar file

### ISSUE THREAD

**Issue by emmauss** [aaubry/YamlDotNet#376]
I have got 2 files, that looks visually the same, but one can be loaded, and the other throws `YamlDotNet.Core.SyntaxErrorException: '(Line: 2, Col: 7, Idx: 12) - (Line: 2, Col: 7, Idx: 12): Mapping values are not allowed in this context.'`
I even copy-pasted the whole document from the working one to the failed doc, still throws error.
 here they are:

Working
[layout.txt](https://github.com/aaubry/YamlDotNet/files/2718229/layout.txt)

how it looks:
```yaml
---
layout:
  - hbox:
    - vbox:
      - layout:
        - width: 100
      - button:
          - id: menuButton
          - label: Buttons
      - button: 
          - id: menuCheckbox
          - label: Checkboxes
    - frame:
      - id: contentFrame
```

failed:
[demo.txt](https://github.com/aaubry/YamlDotNet/files/2718219/demo.txt)

how it looks
```yaml
---
layout:
  - hbox:
    - vbox:
      - layout:
        - width: 100
      - button:
          - id: menuButton
          - label: Buttons
      - button: 
          - id: menuCheckbox
          - label: Checkboxes
    - frame:
      - id: contentFrame
```

the only way I could make it work for other documents is to copy the working file, and edit it from the 3rd line
