### ISSUE TITLE
Default to ScalarStyle.Literal for multiline string

### ISSUE THREAD

**Issue by hbuckle** [aaubry/YamlDotNet#391]
I am serializing a JSON response from an API to YAML and I would like multi-line strings to be serialized using ScalarStyle.Literal instead of Folded
I don't know the structure up front so I can't create classes with the YamlMember attributes - is there anyway to default to ScalarStyle.Literal instead of Folded?

I'm working from PowerShell

```powershell
Add-Type -Path "C:\Users\hbuckle\Downloads\YamlDotNet.dll"
$serializer = [YamlDotNet.Serialization.SerializerBuilder]::new().Build()
$test = @{
  string    = "string"
  multiline = "multi`nline"
}
$yaml = $serializer.Serialize($test)
$yaml | Set-Content "test.yaml"
```

Actual output

```yaml
multiline: >-
  multi

  line
string: string
```

Desired output

```yaml
multiline: |-
  multi
  line
string: string
```
