### ISSUE TITLE
How to use YamlDotNet with dynamic Yamls?

### ISSUE THREAD

**Issue by xalexslx** [aaubry/YamlDotNet#413]
Hi,

I haven't found a discussion page or something so I'll post it here maybe you guys can help me. I'm using YamlDotNet to read a plugin configuration of my application.

Let's say this structure:
```
general:
  conf1: "teste"
  conf2: 1
  conf3: true

optional:
  conf4: "teste"
  conf5: 1
  conf6: true
  conf7:
    - a
    - b
    - c
  conf8:
    - name: test1
      value: 1
    - name: test2
      value: 2
    - name: test3
      value: 3
```

general is my required config files which my main application will read. However, how can I use YamlDotNet to read non required and dynamic configurations such the one under 'optional'?

I would like to read it and store so my plugin can read it when it needs so I can simplify plugin configuration management.
