### ISSUE TITLE
Yaml support for aliases?

### ISSUE THREAD

**Issue by YvesR** [aaubry/YamlDotNet#433]
Hello,

does YamlDotNet support using aliases in yml files?

Example
```
production: &default
  adapter: sqlserver
  mode: dblib
  host: localhost
  dataserver: localhost
  port: 1433
  database: latest
  username: xxxxx
  password: yyyyyyyy
  timeout: 10000
  reconnect: true

development:
  <<: *default
```

If so, where can I find an implantation example? Did not find any so far.
