### ISSUE TITLE
Can't deserialize readonly properties 

### ISSUE THREAD

**Issue by buddhikac96** [aaubry/YamlDotNet#500]
When trying to deserialize a class which has readonly property, throw exception `Type not found`.

`[System.Runtime.Serialization.SerializationException: Property 'name' not found on type 'Student'.]`

```C#
public class Student{
	
	public readonly string name;
	public readonly string email;
	public readonly string school;

}
```

```yaml
name: buddhika
email: buddhika@gmail.com
school: UoM
```
