### ISSUE TITLE
YamlDotNet merges anchor list in wrong order.

### ISSUE THREAD

**Issue by Indomitable** [aaubry/YamlDotNet#594]
Hello,

According the documentation: https://yaml.org/type/merge.html 
> Keys in mapping nodes earlier in the sequence override keys specified in later mapping nodes

Considering this example:
```yaml
.first: &first
  x: 1
.second: &second
  x: 2

item:
  <<: [*second, *first]
```
element item.x should have value 2, but YamlDotNet produces value 1
Sample project can be found here: https://github.com/Indomitable/yaml-merge-bug
![image](https://user-images.githubusercontent.com/1831191/110525645-203b8500-8115-11eb-82c0-f41b3c1c19da.png)

BR
