### ISSUE TITLE
Incorrect Line called out with issue found

### ISSUE THREAD

**Issue by QualityRobD** [aaubry/YamlDotNet#625]
**Describe the bug**
I have some sample yaml that has an issue (missing quote) on line 16, however the callout supplied by YamlDotNet is for line 34.

**To Reproduce**
See below for the sample

Sample
```yaml
attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

deploy_nonprod_job: &deploy_nonprod_job
    working_directory: '~/build'
    docker: [ {image: 'test.com'} ]
    steps:
        - *attach_workspace
        - run: 'deploy-to-test'

version: 2

jobs:
    build_test_image:
        working_directory: '~/build
        docker:
            - image: docker:17.05.0-ce-git
        environment:
            DOCKER_IMAGE_NAME: testApp
        steps:
            - run:
                name: Install bash and curl
                command: |
                    apk update
                    apk add -y curl
                    apk add -y bash
                    apk update
                    apk upgrade

    deploy_test:
        environment:
            HAL_TARGETS: '45597'
            HAL_BUILD_FILE: '.hal_build_id_test'

workflows:
    version: 2
    pipeline:
        jobs:        
            - build_test_image
            - deploy_test

```

output: 
```
(Line: 34, Col: 27, Idx: 820) - (Line: 34, Col: 27, Idx: 820): While scanning a plain scalar value, found invalid mapping.
```

the exact same yaml on yamllint.com providing the correct line number with the issue:
![image](https://user-images.githubusercontent.com/17755173/128035969-e827a2a4-7916-4130-a38f-911f091c3f39.png)

**Comment by yamldotnet** [comment]
> ```yaml
> attach_workspace: &attach_workspace
>     attach_workspace:
>         at: '.'
> 
> deploy_nonprod_job: &deploy_nonprod_job
>     working_directory: '~/build'
>     docker: [ {image: 'test.com'} ]
>     steps:
>         - *attach_workspace
>         - run: 'deploy-to-test'
> 
> version: 2
> 
> jobs:
>     build_test_image:
>         working_directory: '~/build
>         docker:
>             - image: docker:17.05.0-ce-git
>         environment:
>             DOCKER_IMAGE_NAME: testApp
>         steps:
>             - run:
>                 name: Install bash and curl
>                 command: |
>                     apk update
>                     apk add -y curl
>                     apk add -y bash
>                     apk update
>                     apk upgrade
> 
>     deploy_test:
>         environment:
>             HAL_TARGETS: '45597'
>             HAL_BUILD_FILE: '.hal_build_id_test'
> 
> workflows:
>     version: 2
>     pipeline:
>         jobs:        
>             - build_test_image
>             - deploy_test
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 16, char 36: Unexpected '\x0a'

**Comment by QualityRobD** [comment]
It's very interesting that the auto-formatter here called out the correct line. I wonder if my implementation of YamlDotNet is incorrect. I'll supply that shortly.

**Comment by QualityRobD** [comment]
Here is how I am implementing YamlDotNet. Ideally, I would like to point the user to the correct offending line, which I have not been able to do. Right now I am posting a github comment on the first changed line in their Pull Request, which is far from ideal.

```c#
namespace TestApp.BusinessLayer.Analysis.Utilities
{
    public class YamlChecker : IYamlChecker
    {
        public void CheckYaml(string fileData, string fileName, int positionNumber, string commitSha, List<ScanResult> issues)
        {
            ValidateYaml(fileData, fileName, positionNumber, commitSha, issues);
        }

        public static void ValidateYaml(string fileData, string fileName, int positionNumber, string commitSha, List<ScanResult> issues)
        {
            try
            {
                var deserializer = new DeserializerBuilder()
                    .IgnoreUnmatchedProperties()
                    .WithNodeTypeResolver(new MapTagsToObject())
                    .Build();
                deserializer.Deserialize<object>(fileData);
            }
            catch (Exception e)
            {
                // capture failed deserialization information
                var result = new ScanResult
                {
                    FileName = fileName,
                    Issue = "SYNTAX ERROR: YAML failed to validate - **please check entire file (not just this line).**<br/>",
                    Commit = commitSha,
                    IssueContext = e.Message,
                    LineNumber = positionNumber,
                    PositionNumber = positionNumber
                };
                issues.Add(result);
            }
        }
    }

    // Provided by YamlDotNet owner to help ignore custom tags for things like MKdocs
    // https://github.com/aaubry/YamlDotNet/issues/615#issuecomment-861575357
    internal class MapTagsToObject : INodeTypeResolver
    {
        public bool Resolve(NodeEvent? nodeEvent, ref Type currentType)
        {
            if (nodeEvent != null && !nodeEvent.Tag.IsEmpty)
            {
                currentType = typeof(object);
                return true;
            }
            return false;
        }
    }
}
```

**Comment by yamldotnet** [comment]
> ```yaml
> attach_workspace: &attach_workspace
>     attach_workspace:
>         at: '.'
> 
> deploy_nonprod_job: &deploy_nonprod_job
>     working_directory: '~/build'
>     docker: [ {image: 'test.com'} ]
>     steps:
>         - *attach_workspace
>         - run: 'deploy-to-test'
> 
> version: 2
> 
> jobs:
>     build_test_image:
>         working_directory: '~/build
>         docker:
>             - image: docker:17.05.0-ce-git
>         environment:
>             DOCKER_IMAGE_NAME: testApp
>         steps:
>             - run:
>                 name: Install bash and curl
>                 command: |
>                     apk update
>                     apk add -y curl
>                     apk add -y bash
>                     apk update
>                     apk upgrade
> 
>     deploy_test:
>         environment:
>             HAL_TARGETS: '45597'
>             HAL_BUILD_FILE: '.hal_build_id_test'
> 
> workflows:
>     version: 2
>     pipeline:
>         jobs:        
>             - build_test_image
>             - deploy_test
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 16, char 36: Unexpected '\x0a'

**Comment by yamldotnet** [comment]
> ```yaml
> attach_workspace: &attach_workspace
>     attach_workspace:
>         at: '.'
> 
> deploy_nonprod_job: &deploy_nonprod_job
>     working_directory: '~/build'
>     docker: [ {image: 'test.com'} ]
>     steps:
>         - *attach_workspace
>         - run: 'deploy-to-test'
> 
> version: 2
> 
> jobs:
>     build_test_image:
>         working_directory: '~/build
>         docker:
>             - image: docker:17.05.0-ce-git
>         environment:
>             DOCKER_IMAGE_NAME: testApp
>         steps:
>             - run:
>                 name: Install bash and curl
>                 command: |
>                     apk update
>                     apk add -y curl
>                     apk add -y bash
>                     apk update
>                     apk upgrade
> 
>     deploy_test:
>         environment:
>             HAL_TARGETS: '45597'
>             HAL_BUILD_FILE: '.hal_build_id_test'
> 
> workflows:
>     version: 2
>     pipeline:
>         jobs:        
>             - build_test_image
>             - deploy_test
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 16, char 36: Unexpected '\x0a'

**Comment by EdwardCooke** [comment]
Mostly a note to me. This is caused by a difference between the yaml spec 1.1 and 1.2. Requiring the space at the front will violate the 1.1 spec and most likely break current users that rely on 1.1. This needs to be a feature that is turned on by user code, probably a 1.2 enforcement option. At least until we possibly default to 1.2 parsing. I’ll work on this more when I’ve completed more of the smaller low hanging fruit bugs.

**Comment by EdwardCooke** [comment]
After rechecking my thoughts on what was expected in the spec, in 1.1, it is expected that the value be indented by an additional space when the value was already indented.
For example, these 2 are should be, according to the spec, be valid:
```yaml
a:
 b: 'c
  d'
```

```yaml
'hello
world'
```

We should be good once the PR is approved.
