### ISSUE TITLE
Escaped Backslashes gets unescaped  

### ISSUE THREAD

**Issue by YasserGersy** [aaubry/YamlDotNet#629]
I have the following yaml 

```
    matchers:
      - type: status
        status:
          - 200
          - 400
        condition: or
      - type: regex
        regex:
          - "((u|g)id|groups)=[0-9]{1,4}\\([a-z0-9]+\\)"
        part: body
```

Which gets deserialized to an object of  matchers : when i invoke matchers[0].regex[0]:   it returns a different value , the pattern was unescaped  to :

```
((u|g)id|groups)=[0-9]{1,4}\([a-z0-9]+\)
```

Which has a different meaning.
