### ISSUE TITLE
Unexpected artifacts in the resultant YAML

### ISSUE THREAD

**Issue by samsmithnz** [aaubry/YamlDotNet#657]
**Describe the bug**
When generating YAML for a [Dependabot configuration](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit), I unexpectedly get `&o0` and `*o0` artifacts, and sometimes the YAML is truncated

**Observed output** note `&o0` and `*o0`, and additionally, the second `schedule` is missing an `interval: daily` child node
```
version: 2
updates:
- package_ecosystem: nuget
  directory: /
  schedule: &o0
    interval: daily
  attendees:
  - Sam
- package_ecosystem: github-actions
  directory: /
  schedule: *o0
  attendees:
  - Sam
```

**Expected output:**
```
version: 2
updates:
- package_ecosystem: nuget
  directory: /
  schedule:
    interval: daily
  attendees:
  - Sam
- package_ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  attendees:
  - Sam
```

**To Reproduce**
This code snippet reproduces the issue: (.NET 3.1/5/6), and YamlDotNet 11.2.1
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using YamlDotNet.Serialization;

[TestClass]
public class AttendeeTest
{
    [TestMethod]
    public void SerializationTest()
    {
        //Arrange
        var root = new
        {
            version = "2",
            updates = new[] {
                    new {
                        package_ecosystem = "nuget",
                        directory = "/",
                        schedule = new {
                            interval= "daily"
                        },
                        attendees = new List<string>()
                        {
                            "Sam"
                        }
                    },
                    new {
                        package_ecosystem = "github-actions",
                        directory = "/",
                        schedule = new {
                            interval= "daily"
                        },
                        attendees = new List<string>()
                        {
                            "Sam"
                        }
                    }
                }
        };

        //Act
        ISerializer serializer = new SerializerBuilder()
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitDefaults)
            .Build();
        string yaml = serializer.Serialize(root);

        //Assert
        string expected = @"version: 2
updates:
- package_ecosystem: nuget
  directory: /
  schedule:
    interval: daily
  attendees:
  - Sam
- package_ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  attendees:
  - Sam
";
        Assert.AreEqual(expected, yaml);
    }
}
```
