### ISSUE TITLE
Retain blank lines in roundtrip

### ISSUE THREAD

**Issue by zsd4yr** [aaubry/YamlDotNet#678]
I am looking to retain the whitespace in a roundtrip serialization/deserialization and I am wondering if there is a good way to do this.

If I serialize the following:
```yaml
parameters:
- name: Foo
  type: string
  default: false
  values:
  - false
  - true

- name: Bar
  type: string
  default: ReadAndWrite
  values:
  - ReadAndWrite
  - ReadOnly
  - WriteOnly
```

And then deserialize back to a file, I end up with this:
```yaml
parameters:
- name: Foo
  type: string
  default: false
  values:
  - false
  - true
- name: Bar
  type: string
  default: ReadAndWrite
  values:
  - ReadAndWrite
  - ReadOnly
  - WriteOnly
```

However, for readability, I would like to retain the whitespace. My use-case is that I am using YamlDotNet to update specific values in my yaml and then deserialize it back.

I am using dynamic serialization (I don't want to have to write classes for every single permutation of Azure DevOps YAML syntax).

I have already tried using a custom extended [ChainedEventEmitter](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/EventEmitters/ChainedEventEmitter.cs) to insert an arbitrary symbol in front of the value that I then use to indicate a new-line post-deserialization (string-replace), but that is proving fragile in the best case and utterly broken in the worst.

Can I somehow include blank lines as top-level key-value pairs in the dictionary that results from serialization of dynamics? 

Any other ideas?
