### ISSUE TITLE
Decoupling yaml schema from C# class

### ISSUE THREAD

**Issue by dluc** [aaubry/YamlDotNet#691]
Given a yaml configuration like this:
```
myService:
  fileStorage:
    path: myService/data

anotherService:
  foo: 123
  bar: abc
  baz: ex5
```

Is it possible to refactor this code
```
public class MyServiceConfig
{
    [YamlMember(Alias = "myService")]
    public MyServiceConfigProperties MyService { get; set; }

    public class MyServiceConfigProperties
    {
        [YamlMember(Alias = "fileStorage")]
        public FileStorageConfigProperties FileStorage { get; set; }

        public class FileStorageConfigProperties
        {
            [YamlMember(Alias = "path")]
            public string Path { get; set; }
        }
    }
}
```

to a more concise class, e.g. something like this?

```
public class MyServiceConfig
{
    [YamlMember(Alias = "myService:fileStorage:path")]
    public string Path { get; set; }
}
```
