### ISSUE TITLE
Implicit `null` is interpreted as empty string

### ISSUE THREAD

**Issue by flobernd** [aaubry/YamlDotNet#716]
Hi, I' using version `12.0.0` and have the following YAML:

```yaml
on:
  implicit:
  explicit: null
  empty-string: ''
```

During deserialization, the implicit `null` value of `workflow_dispatch` gets interpreted as an empty string `""`:

```csharp
Deserializer.Deserialize<YamlMappingNode>(reader)
```

```yaml
on:
  implicit: ''
  explicit: null
  empty-string: ''
```

Same thing can be observed during serialization when I manually create a `YamlScalarNode` with a `null` value.

For the low level representation as `Yaml{*}Node` I would expect the original format to get preserved. If there was an explicit `null` it should re-serialize as explicit `null` and if there was an implicit `null`, it should re-serialize as implicit `null`. In no case should it re-serialize as `""` imho.

---

When using `Dictionary<object, object>` instead of `YamlMappingNode` as the target type for the deserialization method, everything seems to work fine. Explicit `null` values are emitted as implicit ones at the end, but that's fine in this case I guess.

```csharp
Deserializer.Deserialize<Dictionary<object, object>>(reader)
```

```yaml
on:
  implicit: 
  explicit: 
  empty-string: ''
```
