### ISSUE TITLE
Global toggle for quoting strings when serializing 

### ISSUE THREAD

**Issue by jhm-ciberman** [aaubry/YamlDotNet#791]
**Is your feature request related to a problem? Please describe.**
I am making a mod loader system for a game and I would prefer every string (and maybe enums) to be quoted in double quotes to avoid any confusion for moders (and for myself) when authoring yaml files about special characters.

A typical manifest.yaml file for my game would look like this:
```yaml
!Package
id: "medieval_life"
name: "Medieval Life"
description: "Built-in content for the Medieval Life game."
author: "Ciberman"
version: "1.0.0"
dependencies: []
content:
  - !Image
    id: "textures.water"
    path: "res/water.png"
  - !Image
    id: "textures.cliff"
    path: "res/tilemap/cliff.png"
  - !Image
    id: "textures.particles.smoke"
    path: "res/particles/smoke.png"
  - !GltfAnimation
    id: "animations.idle"
    path: "res/avatar/Character.glb"
    animation_name: "Idle"
  - !GltfAnimation
    id: "animations.walk"
    path: "res/avatar/CharacterWalk.glb"
    animation_name: "Walk"
  - !Image
    id: "textures.luts.hair"
    path: "res/avatar/LutHair.png"
  - !Image
    id: "textures.luts.eyes"
    path: "res/avatar/LutEyes.png"
  - !Object
    id: "furniture.bed"
    name: "Bed"
    description: "A simple bed"
    size: [1, 1]
    collision_shape: !Rectangle
      min: [0, 0]
      max: [2, 1]
    texture: !Image
      path: "res/furniture/bed.png"
    model: !GltfPrefab
      path: "res/furniture/bed.glb"
      model_scale: [1, 1, 1]
  - !Image
    id: "textures.luts.skin"
    path: "res/avatar/LutSkin.png"
  - !Sprite
    id: "gui.button_primary"
    path: "res/gui/button_primary.png"
    size: [32, 32]
    frames: 4
    nine_slice_margin: [8, 2, 6, 8]
    
# More content definitions here...
```

Currently YamlDotNet serializes every string without quotes. 

**Describe the solution you'd like**
I would want a simple togle or simple way to force every string to be quoted. I'm not sure about what the ideal API would be. 

**Describe alternatives you've considered**
I know I can force quoting via `[YamlMember]` attribute, but I would want a global toggle for every serialized string, because It's very cumbersome and easy to forget to add a `YamlMemberAttribute` to every DTO object.

I also spent a lot of time trying to use the solution in [this](https://github.com/aaubry/YamlDotNet/issues/428#issuecomment-525242110) comment but I cannot get it to only quote string values. It quotes everything including property names, which looks ugly to me.

**Additional context**
I'm very happy with YamlDotNet. And Writting custom YamlTypeConverters is very fun. Thanks for your amazing work! ❤️
