### ISSUE TITLE
backreference "<<"

### ISSUE THREAD

**Issue by OxygeneIV** [aaubry/YamlDotNet#8]
Hi, I (think) I do not get the backreference to work as I expect.

For simple referencing I get the substitution I expect :

  btnSignIn: &signin1
    how: css
    what: "div.ScalableButtonRegular,#btnLogin"
  btnSignin2: *signin1  

=>

```
{ btnSignIn, { { how, css }, { what, div.ScalableButtonRegular,#btnLogin } } }, 
{ btnSignin2, { { how, css }, { what, div.ScalableButtonRegular,#btnLogin } } } ....
```

but using referencing like "backreference.yaml" does not substitute fully, "<<" is shown as a key-value.

```
  btnSignIn: &signin1
    how: css
    what: "div.ScalableButtonRegular,#btnLogin"
  btnSignin2:   
    <<: *signin1
    what: newWhatValue
```

```
{ btnSignIn, { { how, css }, { what, div.ScalableButtonRegular,#btnLogin } } }, 
{ btnSignin2, { { <<, { { how, css }, { what, div.ScalableButtonRegular,#btnLogin } } }, { what, newWhatValue } } }
```

and using your "backreference.yaml" also shows "<<" as a key value:

```
parent: 
  anchor: &default 
    key1: value1
    key2: value2
  alias: 
    <<: *default
    key2: Overriding key2
```

```
{[parent, { { anchor, { { key1, value1 }, { key2, value2 } } }, { alias, { { <<, { { key1, value1 }, { key2, value2 } } }, { key2, Overriding key2 } } } }]}	
```

I'd expect "alias" to show { alias, { { key1, value1 }, { key2, Overriding key2 } } }

or do I have to add logic to fix above?

Thanks

/Magnus
