### ISSUE TITLE
Cannot parse YAML file, (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization

### ISSUE THREAD

**Issue by rudolfolah** [aaubry/YamlDotNet#820]
**Describe the bug**

I'm encountering an issue while trying to load an Ansible task file, where I receive an exception related to deserialization.

When attempting to load the Ansible task file, the following exception arises:

```
Unhandled exception. (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
```

**To Reproduce**

Here is the specific C# code I am executing:

```csharp
string tasksMainYaml = File.ReadAllText("../../../sample_data/tasks_main.yml");
var yamlDeserializer = new DeserializerBuilder().Build();
var parser = new Parser(new StringReader(tasksMainYaml));
YamlDotNet.RepresentationModel.YamlStream yaml = new YamlDotNet.RepresentationModel.YamlStream();
yaml.Load(new StringReader(tasksMainYaml));
parser.Expect<StreamStart>();

while (parser.Accept<DocumentStart>())
{
    // Deserialize the document
    var doc = yamlDeserializer.Deserialize<List<string>>(parser);

    Console.WriteLine("## Document");
    foreach (var item in doc)
    {
        Console.WriteLine(item);
    }
}
```

The YAML file that I am trying to parse includes the following:

```yml
---
- name: Install certbot
  tags: setup
  community.general.snap:
    name: certbot
    classic: true
- name: Create symlink for Certbot binary
  tags: setup
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  become: true
- name: Check if the certificate was already generated
  tags: generate_cert
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
  register: cert_fullchain_file
- name: Generate certificate manually
  tags: generate_cert
  ansible.builtin.command:
    cmd: "certbot certonly --standalone --preferred-challenges http --agree-tos --email {{ email }} -d {{ domain }}"
    creates: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
  when: not cert_fullchain_file.stat.exists
```

Any assistance in troubleshooting this issue would be greatly appreciated.
