### ISSUE TITLE
How to forcefully interpret as an array with implied key

### ISSUE THREAD

**Issue by timheuer** [aaubry/YamlDotNet#830]
I'm trying to parse a GitHub Actions workflow file...here's a snippet of valid workflow:

```yaml
name: "Build"

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for the manual run
        required: true
        type: string
      something_else:
        description: Some other input
        required: false
        type: boolean
```

The `inputs` is not resolving to an array, but rather properties of inputs.  If I change these to `-reason` etc then it sees them as an array, but that's not valid workflow syntax.

I'm curious if there is a way I can get the parser to see this as an array where the `reason` portion would be the key?
