### ISSUE TITLE
YamlMember Alias usage

### ISSUE THREAD

**Issue by oqo0** [aaubry/YamlDotNet#849]
I use YamlDotNet to read data from a config file like this:
```yaml
ranks:
  - name: "Name"
    image-path: "assets/ranks/image1.png"
  - name: "Name"
    image-path: "assets/ranks/image2.png"
```
I try to deserialize it to a list of objects like this using IConfiguration:
```cs
public class Rank
{
    [YamlMember(Alias = "name")]
    public string Name { get; set; }

    [YamlMember(Alias = "image-path")]
    public string? Image { get; set; }
}
```
```cs
  builder.ConfigureAppConfiguration(options =>
  {
      options.AddYamlFile("config.yml", false);
  });
```
```cs
_ranks = _configuration.GetSection("ranks").Get<List<Rank>>();
```
When I read ranks from a configuration this way it doesn't work. Image property is always `null`. It looks like `[YamlMember(Alias = "image-path")]` is getting ignored when file is deserizlized.

I tried to change `image-path` property in my config to `image` like this
```yaml
ranks:
  - name: "Name"
    image: "assets/ranks/image1.png"
  - name: "Name"
    image: "assets/ranks/image2.png"
```
And it works properly. `Image` property is getting deserialized to it's config value.

How can I fix this? Is there another attribute for deserialization?

I use YamlDotNet `13.3.1`
net6.0
