### ISSUE TITLE
Order for inheritance

### ISSUE THREAD

**Issue by Develeon64** [aaubry/YamlDotNet#870]
Hello there!

The question in short is: Can I change to order, so the members of inherited classes get serialized first, without manually sorting everything?

More info:
I want to use YAML to configure my app. Every time I read the configuration file I write the just read contents back to normalize it. For my logger I have a base class defining two members, that every logger should have:
```csharp
public abstract class LogConfigBase {
    public bool Enabled { get; set; } = false;
    public byte Level   { get; set; } = 0;
}
```
And now I'm using this to define the default behavior of all loggers and 3 specific ones:
```csharp
public class LogConfig : LogConfigBase {
    public LogConsoleConfig Console { get; set; } = new();
    public LogFileConfig    File    { get; set; } = new();
    public LogSystemConfig  System  { get; set; } = new();
}
```
```csharp
public class LogConsoleConfig : LogConfigBase {
    public bool Colorized { get; set; } = true;
}
```
```csharp
public class LogFileConfig : LogConfigBase {
    public string Path { get; set; } = "Logs/";
}
```
```csharp
public class LogSystemConfig : LogConfigBase {
    public int Id { get; set; } = 0;
}
```

When serializing this the inherited members are placed behind every other members. But I'd like them to be always at the top.
```yaml
logging:
  enabled: true
  level: 1
  console:
    enabled: true
    level: 1
    colorized: true
  file:
    enabled: true
    level: 3
    path: Logs/
  system:
    enabled: true
    level: 5
    id: 1234567890
```
Instead of
```yaml
logging:
  console:
    colorized: true
    enabled: true
    level: 1
  file:
    path: Logs/
    enabled: true
    level: 3
  system:
    id: 1234567890
    enabled: true
    level: 5
  enabled: true
  level: 1
```
Can I achieve this in a quick and simple way without creating a custom SortedTypeInspector?
