### ISSUE TITLE
How to serialize  the !include Directive in YamlDotNet

### ISSUE THREAD

**Issue by martindybal** [aaubry/YamlDotNet#880]
Description:

I have a YAML configuration that includes external files using the !include directive, like this:

```yaml

views:
  - !include views/home.yaml
  - title: Světnice
    path: dashboard
    badges: ...
```      
      
I'm using YamlDotNet for YAML serialization in my C# project, and I'm wondering how to properly serialize this YAML structure while ensuring that the !include directive is correctly processed to include external files.

I'm tried 

```C#
            views = new[]
            {
                new YamlScalarNode("!include views/home.yaml"),
                new
                {
                    title = dashboard.Title,
                    path = dashboard.UrlSlug,
                    badges = dashboard.GetBadges().Select(badge => badge.ToYml()),
                    cards = dashboard.GetCards().Select(card => card.ToYml())
                }.ToYml(),
            }
```

also 

```C#
            views = new object[]
            {
                "!include views/home.yaml",
                new
                {
                    title = dashboard.Title,
                    path = dashboard.UrlSlug,
                    badges = dashboard.GetBadges().Select(badge => badge.ToYml()),
                    cards = dashboard.GetCards().Select(card => card.ToYml())
                },
            }
```

The result is both cases the same: 

```yaml

views:
- '!include views/home.yaml'  #this should not be a string
- title: Světla
  path: lovelace-lights
  badges:  ...
```     

Is there something like `RawYamlNode` ?
