### ISSUE TITLE
Questions about Custom Serialization

### ISSUE THREAD

**Issue by cd-zhang2020** [aaubry/YamlDotNet#890]
Hello，Is it possible to add attributes to specified fields to implement a custom serialization and deserialization method?

For example   Newtonsoft.Json

[JsonConverter(typeof(CustomConverter))]

` var serializer = new SerializerBuilder()
                .WithTypeConverter(new CustomConverter())
                .Build();`

I use the above code to customize the serialization, but this is a global method

**Comment by EdwardCooke** [comment]
Not that I’m aware of. You’d need to have multiple builders to do different type converters like your asking about.

**Comment by cd-zhang2020** [comment]
@EdwardCooke Thank you for your answer，The functionality I want to implement cannot be handled with different types converters。
For example
` serverConnector:
   #Descirption: id of server connector.
   id: server1
   addresses:
     - 127.0.0.1:8091
   protocol: grpc
   connectTimeout: 500ms
   messageTimeout: 5s
   connectionIdleTimeout: 60s
   serverSwitchInterval: 10m
   reconnectInterval: 500ms`

Deserialize the string 500ms into the number 500, and deserialize the string 5s into the number 5000

**Comment by cd-zhang2020** [comment]
@EdwardCooke Thank you for your answer，The functionality I want to implement cannot be handled with different types converters。

For example 
```
serverConnector:
   id: server1
   addresses:
     - 127.0.0.1:8091
   protocol: grpc
   connectTimeout: 500ms
   messageTimeout: 5s
   connectionIdleTimeout: 60s
   serverSwitchInterval: 10m
   reconnectInterval: 500ms
``` 

Deserialize the string 500ms into the number 500, and deserialize the string 5s into the number 5000，I can't convert all strings to numbers
