### ISSUE TITLE
Including (parts of) anotehr YAML file

### ISSUE THREAD

**Issue by mikhail-barg** [aaubry/YamlDotNet#909]
I'd like to re-open the problem raised here: https://github.com/aaubry/YamlDotNet/issues/368

The proposed solution with custom tags does basically work, but it has the problem [explained by @rcdailey](https://github.com/aaubry/YamlDotNet/issues/368#issuecomment-1689074678): the `INodeDeserializer.Deserialize` method should return already parsed/converted type, but it has no info on the type expected by the model.

I was able to implement some basic `include` tag deserializer that works in general like this:

```yaml
      location: http://some.example/api
      auth:
        user: !include secret.yaml#auth.user
        pass: !include secret.yaml#auth.pass
```

But it's only ok while the populated fields expect strings. But this is not always the case.

For example following will not work:

```yaml
      host: !include secret.yaml#loc.host
      port: !include secret.yaml#loc.port
```
given that `port` is an `int`:

```c#
public sealed class Location
{
   public string host { get; set; }
   public int port { get; set; }
}
```

One workaround here would be to substitute the `int port` with a wrapper class having a [`Parse`](https://github.com/aaubry/YamlDotNet/blob/19d7875b240c28516ef24c40485e29eaca9b9418/YamlDotNet/Serialization/Utilities/TypeConverter.cs#L226) method:
```
public sealed class IntWrapper
{
   public int value { get; set; }

   public static IntWrapper Parse(string v) { 
      return new IntWrapper() {
         value = Int32.Parse(v)
      };
   }
}

public sealed class Location
{
   public string host { get; set; }
   public IntWrapper port { get; set; }
}
```

But this is kinda ugly and troublesome.

Also this means that there's no actual way to include structured classes (without manually re0inventing parsing for them second time). For example instead on this
```yaml
      location: http://some.example/api
      auth:
        user: !include secret.yaml#auth.user
        pass: !include secret.yaml#auth.pass
```
i'd like to use 
```yaml
      location: http://some.example/api
      auth: !include secret.yaml#auth
```

So it would be really nice to have either a way to provide `INodeDeserializer.Deserialize()` with expected type info.

OR have a standard way to inject parts of external yaml streams into the main parser at specified places. Maybe some magic with MergingParser?

**Comment by EdwardCooke** [comment]
Did the above answer your question?

**Comment by mikhail-barg** [comment]
@EdwardCooke Hi! sorry for a late answer, I've missed notifications (

Getting back to your solution, what bugs me, is that line:

```c#
var result = deserializer.Deserialize<Auth>(yaml);
```

How do I know that it's the `Auth` object expected at the place of `!include`? If I get your solution right, it requires knowing expected type upfront, and therefore I would not be able to make both 

```yaml
      location: http://some.example/api
      auth:
        user: !include secret.yaml#auth.user
        pass: !include secret.yaml#auth.pass
```
and 
```
      location: http://some.example/api
      auth: !include secret.yaml#auth
```

to work?
